name: Release

permissions:
  contents: write

on:
  release:
    types: [ published ]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Java with Gradle cache
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build libgtk-3-dev

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Cache Pub packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - run: flutter pub get

      - name: Setup Keystore
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > android/my_alarms-keystore.jks
          echo "storePassword=$KEYSTORE_PASSWORD" > android/key.properties
          echo "keyPassword=$KEY_PASSWORD" >> android/key.properties
          echo "keyAlias=$KEY_ALIAS" >> android/key.properties
          echo "storeFile=../my_alarms-keystore.jks" >> android/key.properties
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}


      - name: Update version in pubspec.yaml
        run: |
          VERSION=${{ github.ref_name }}
          VERSION=${VERSION#v}
          
          if ! [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+([+-][^[:space:]]+)?$ ]]; then
            echo "Version invalide ($VERSION), utilisation de 0.0.0-nightly"
            VERSION="0.0.0-nightly"
          fi
          
          sed -i "s/^version: .*/version: $VERSION/" pubspec.yaml
          echo "Version set to: $VERSION"
          grep version pubspec.yaml

      - run: flutter build apk --release --split-per-abi --no-pub

      - name: Rename APKs with version
        run: |
          for APK in build/app/outputs/flutter-apk/*.apk; do
            mv "$APK" "alarm-${{ github.ref_name }}-${APK}"
          done
          
          mv "build/app/outputs/bundle/debug/app-debug.aab" "build/app/outputs/bundle/debug/alarm-${{ github.ref_name }}-app-debug.aab"

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: alarms-android
          path: |
            build/app/outputs/flutter-apk/*.apk
            build/app/outputs/bundle/debug/*.aab
          compression-level: 0
          retention-days: 7

      - run: flutter build appbundle --release --no-pub

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/app/outputs/flutter-apk/*.apk
            build/app/outputs/bundle/debug/*.aab

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#  build-ios:
#    name: Build for iOS
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: Set up Flutter
#        uses: subosito/flutter-action@v2
#        with:
#          channel: 'stable'
#          architecture: x64
#      - run: flutter pub get
#      - run: flutter build ios --release --no-pub --no-codesign
